trigger:
  branches:
    include:
      - '*'
  tags:
    include:
      - v*
variables:
  CIBW_BUILDING: "true"
  CIBW_SKIP: "cp27-* cp34-*"
#  CIBW_TEST_REQUIRES: "pytest"
#  CIBW_TEST_COMMAND: "pytest"
  CIBW_BUILD_VERBOSITY: "2"
  CIBW_BEFORE_BUILD: "pip install -U Cython"
jobs:
- job: linux
  pool: {vmImage: 'Ubuntu-18.04'}
  timeoutInMinutes: 40
  steps:
    - checkout: self
      submodules: true
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
    - bash: |
        python -m pip install --upgrade pip
        pip install cibuildwheel==1.5.5 cython
        cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}
- job: macos
  pool: {vmImage: 'macOS-10.15'}
  timeoutInMinutes: 40
  steps:
    - checkout: self
      submodules: true
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.8'
    - bash: |
        python -m pip install --upgrade pip
        pip install cibuildwheel==1.5.5 cython
        cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}
- job: windows
  pool: {vmImage: 'vs2017-win2016'}
  timeoutInMinutes: 40
  steps:
    - checkout: self
      submodules: true
#    - {task: UsePythonVersion@0, inputs: {versionSpec: '2.7', architecture: x86}}
#    - {task: UsePythonVersion@0, inputs: {versionSpec: '2.7', architecture: x64}}
    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.5', architecture: x86}}
    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.5', architecture: x64}}
    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.6', architecture: x86}}
    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.6', architecture: x64}}
    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.7', architecture: x86}}
    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.7', architecture: x64}}
    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.8', architecture: x86}}
    - {task: UsePythonVersion@0, inputs: {versionSpec: '3.8', architecture: x64}}
    - script: choco install vcpython27 -f -y
      displayName: Install Visual C++ for Python 2.7
    - bash: |
        python -m pip install --upgrade pip
        pip install cibuildwheel==1.5.5 cython
        cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}

